export const specialties: string[] = [
  'General Physician',
  'Pediatrics / Child Care',
  'Gynaecology',
  'Neurology / Brain',
  'Pulmonology / Lungs',
  'Nutritionist',
  'Gastroenterology',
  'Cardiology / Heart',
  'Ophthalmology / Eye',
  'Dentistry / Dental Care',
  'Endocrinology / Diabetes',
  'Occupational therapy',
  'Nephrology / Kidney',
  'Obstetrics',
  'ENT / Ear, Nose and Throat',
  'Parasitology',
  'Podiatry',
  'Oncology',
  'Dermatology',
  'Psychological counsellor',
  'Rheumatology',
  'Urology',
  'Chiropractic',
];
